#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new \App\Command\UpCommand());
$application->add(new \App\Command\BuildCommand());

// FIXME: auto create docker-compose.custom.yml

$application->run();
