version: '3'
services:
  apache:
    image: httpd:2.4
    container_name: dockstead-apache
    ports:
      - '8000:80'
    volumes:
      - ./apache/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache/conf/v-hosts:/usr/local/apache2/conf/v-hosts
    networks:
      - dockstead

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    image: dockstead/php
    container_name: dockstead-php
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # environment:
    #   XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
    #   XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    volumes:
      - ./php/conf/7.4/fpm/php.ini:/etc/php/7.4/fpm/php.ini
      - ./php/conf/7.4/fpm/php-fpm.ini:/etc/php/7.4/fpm/php-fpm.ini
      - ./php/conf/7.4/fpm/pool.d/www.conf:/etc/php/7.4/fpm/pool.d/www.conf 
    networks:
      - dockstead

  mysql-5.7:
    image: mysql:5.7
    platform: linux/amd64
    container_name: dockstead-mysql-5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "homestead"
      MYSQL_USER: "homestead"
      MYSQL_PASSWORD: "secret"
      MYSQL_INITDB_SKIP_TZINFO: 1
    ports:
      - '33060:3306'
    volumes:
      - ./database/mysql/5.7/conf.d:/etc/mysql/conf.d
      - dockstead-mysql-5.7:/var/lib/mysql
    networks:
      - dockstead

networks:
  dockstead:
    driver: bridge

volumes:
  dockstead-mysql-5.7:
