version: '3'
services:
  apache:
    image: httpd:2.4
    container_name: dockstead-apache
    ports:
      - '8000:80'
    volumes:
      - ./apache/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache/conf/v-hosts:/usr/local/apache2/conf/v-hosts
    networks:
      - sail

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    image: dockstead/php
    container_name: dockstead-php
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # environment:
    #   XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
    #   XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    volumes:
      - ./php/conf/7.4/fpm/php.ini:/etc/php/7.4/fpm/php.ini
      - ./php/conf/7.4/fpm/php-fpm.ini:/etc/php/7.4/fpm/php-fpm.ini
      - ./php/conf/7.4/fpm/pool.d/www.conf:/etc/php/7.4/fpm/pool.d/www.conf 
    networks:
      - sail

networks:
  sail:
    driver: bridge
